# Change these first
owner: tornadocontrib # Your GitHub organization or username, where this repository lives
repo: unruggable-upptime # The name of this repository

sites:
  - name: Arbitrum One Mainnet
    icon: https://assets.coingecko.com/coins/images/16547/standard/arb.jpg
    url: https://arbitrum.gateway.unruggable.com

  - name: Base Mainnet
    icon: https://raw.githubusercontent.com/base-org/brand-kit/refs/heads/main/logo/symbol/Base_Symbol_Blue.png
    url: https://base.gateway.unruggable.com

  - name: Optimism Mainnet
    icon: https://assets.coingecko.com/coins/images/25244/standard/Optimism.png
    url: https://optimism.gateway.unruggable.com

  - name: Linea Mainnet
    icon: https://linea.build/_next/static/media/logomark.1510dc60.svg
    url: https://linea.gateway.unruggable.com

  - name: Scroll Mainnet
    icon: https://assets.coingecko.com/coins/images/50571/standard/scroll.jpg
    url: https://scroll.gateway.unruggable.com

  - name: Self Mainnet
    icon: https://assets.coingecko.com/coins/images/279/standard/ethereum.png
    url: https://self.gateway.unruggable.com

  - name: Arbitrum One Sepolia
    icon: https://assets.coingecko.com/coins/images/16547/standard/arb.jpg
    url: https://arbitrum-sepolia.gateway.unruggable.com

  - name: Base Sepolia
    icon: https://raw.githubusercontent.com/base-org/brand-kit/refs/heads/main/logo/symbol/Base_Symbol_Blue.png
    url: https://base-sepolia.gateway.unruggable.com

  - name: Optimism Sepolia
    icon: https://assets.coingecko.com/coins/images/25244/standard/Optimism.png
    url: https://optimism-sepolia.gateway.unruggable.com

  - name: Linea Sepolia
    icon: https://linea.build/_next/static/media/logomark.1510dc60.svg
    url: https://linea-sepolia.gateway.unruggable.com

  - name: Scroll Sepolia
    icon: https://assets.coingecko.com/coins/images/50571/standard/scroll.jpg
    url: https://scroll-sepolia.gateway.unruggable.com

  - name: Self Sepolia
    icon: https://assets.coingecko.com/coins/images/279/standard/ethereum.png
    url: https://self-sepolia.gateway.unruggable.com

  - name: Trusted Sepolia
    icon: https://assets.coingecko.com/coins/images/279/standard/ethereum.png
    url: https://trusted-sepolia.gateway.unruggable.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Unruggable Gateways Upptime
  introTitle: "**Unruggable Gateways Upptime**"
  introMessage: Status page to track Unruggable Gateways Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Unruggable
      href: https://unruggable.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
